import type { CalendarEventItem, CalendarFilter } from "@/components/calendar/types";
import { addDays, dateKey, startOfWeek } from "@/lib/date-utils";

export const calendarFilters: CalendarFilter[] = [
  {
    id: "primary",
    label: "User Profile",
    accentClass: "accent-blue-600",
    checked: true,
    tone: "blue",
  },
  {
    id: "birthdays",
    label: "Birthdays",
    accentClass: "accent-teal-600",
    checked: true,
    tone: "teal",
  },
  {
    id: "tasks",
    label: "Tasks",
    accentClass: "accent-amber-500",
    checked: true,
    tone: "amber",
  },
];

export const timeLabels = [
  "1 AM",
  "2 AM",
  "3 AM",
  "4 AM",
  "5 AM",
  "6 AM",
  "7 AM",
  "8 AM",
  "9 AM",
  "10 AM",
  "11 AM",
  "12 PM",
  "1 PM",
  "2 PM",
  "3 PM",
  "4 PM",
  "5 PM",
  "6 PM",
  "7 PM",
  "8 PM",
  "9 PM",
  "10 PM",
  "11 PM",
];

export function createInitialEvents(anchorDate: Date): CalendarEventItem[] {
  const weekStart = startOfWeek(anchorDate);

  return [
    {
      id: "evt-weekly-sync",
      title: "Weekly Sync",
      date: dateKey(weekStart),
      startMinutes: 9 * 60,
      endMinutes: 10 * 60 + 30,
      allDay: false,
      calendarId: "primary",
      tone: "blue",
      type: "event",
      location: "Google Meet",
      description: "Team planning and blockers.",
    },
    {
      id: "evt-client-lunch",
      title: "Lunch with Client",
      date: dateKey(addDays(weekStart, 2)),
      startMinutes: 13 * 60,
      endMinutes: 14 * 60,
      allDay: false,
      calendarId: "birthdays",
      tone: "teal",
      type: "event",
      location: "Downtown Cafe",
    },
    {
      id: "evt-retreat-1",
      title: "Company Retreat",
      date: dateKey(addDays(weekStart, 3)),
      startMinutes: 9 * 60,
      endMinutes: 17 * 60,
      allDay: true,
      calendarId: "primary",
      tone: "blue",
      type: "event",
    },
    {
      id: "evt-retreat-2",
      title: "Company Retreat",
      date: dateKey(addDays(weekStart, 4)),
      startMinutes: 9 * 60,
      endMinutes: 17 * 60,
      allDay: true,
      calendarId: "primary",
      tone: "blue",
      type: "event",
    },
    {
      id: "evt-deep-work",
      title: "Deep Work",
      date: dateKey(addDays(weekStart, 4)),
      startMinutes: 15 * 60,
      endMinutes: 17 * 60,
      allDay: false,
      calendarId: "primary",
      tone: "violet",
      type: "event",
      description: "Focus block for project work.",
    },
    {
      id: "task-report",
      title: "Submit weekly report",
      date: dateKey(addDays(weekStart, 5)),
      startMinutes: 9 * 60,
      endMinutes: 10 * 60,
      allDay: true,
      calendarId: "tasks",
      tone: "amber",
      type: "task",
    },
  ];
}
