import type { CalendarEventItem, CalendarFilter } from "@/components/calendar/types";
import { addDays, dateKey, startOfWeek } from "@/lib/date-utils";

export const calendarFilters: CalendarFilter[] = [
  {
    id: "science",
    label: "Science",
    accentClass: "accent-blue-600",
    checked: true,
    tone: "blue",
  },
  {
    id: "humanities",
    label: "Humanities",
    accentClass: "accent-teal-600",
    checked: true,
    tone: "teal",
  },
  {
    id: "maths",
    label: "Mathematics",
    accentClass: "accent-violet-600",
    checked: true,
    tone: "violet",
  },
  {
    id: "arts",
    label: "Arts & PE",
    accentClass: "accent-amber-500",
    checked: true,
    tone: "amber",
  },
  {
    id: "language",
    label: "Language",
    accentClass: "accent-rose-500",
    checked: true,
    tone: "rose",
  },
];

export const timeLabels = [
  "1 AM",
  "2 AM",
  "3 AM",
  "4 AM",
  "5 AM",
  "6 AM",
  "7 AM",
  "8 AM",
  "9 AM",
  "10 AM",
  "11 AM",
  "12 PM",
  "1 PM",
  "2 PM",
  "3 PM",
  "4 PM",
  "5 PM",
  "6 PM",
  "7 PM",
  "8 PM",
  "9 PM",
  "10 PM",
  "11 PM",
];

export function createInitialEvents(anchorDate: Date): CalendarEventItem[] {
  const weekStart = startOfWeek(anchorDate);
  // Mon=1, Tue=2, Wed=3, Thu=4, Fri=5
  const mon = addDays(weekStart, 1);
  const tue = addDays(weekStart, 2);
  const wed = addDays(weekStart, 3);
  const thu = addDays(weekStart, 4);
  const fri = addDays(weekStart, 5);

  return [
    // ── MONDAY ──
    {
      id: "cls-mon-1",
      title: "Mathematics",
      subject: "Mathematics",
      teacher: "Mr. Arjun Sharma",
      date: dateKey(mon),
      startMinutes: 8 * 60,
      endMinutes: 9 * 60,
      allDay: false,
      calendarId: "maths",
      tone: "violet",
      type: "event",
      location: "Room 101",
    },
    {
      id: "cls-mon-2",
      title: "Physics",
      subject: "Physics",
      teacher: "Ms. Priya Nair",
      date: dateKey(mon),
      startMinutes: 9 * 60 + 15,
      endMinutes: 10 * 60 + 15,
      allDay: false,
      calendarId: "science",
      tone: "blue",
      type: "event",
      location: "Lab 2",
    },
    {
      id: "cls-mon-3",
      title: "English Literature",
      subject: "English",
      teacher: "Mrs. Sunita Verma",
      date: dateKey(mon),
      startMinutes: 11 * 60,
      endMinutes: 12 * 60,
      allDay: false,
      calendarId: "language",
      tone: "rose",
      type: "event",
      location: "Room 204",
    },
    {
      id: "cls-mon-4",
      title: "History",
      subject: "History",
      teacher: "Mr. Ravi Kulkarni",
      date: dateKey(mon),
      startMinutes: 13 * 60,
      endMinutes: 14 * 60,
      allDay: false,
      calendarId: "humanities",
      tone: "teal",
      type: "event",
      location: "Room 305",
    },
    {
      id: "cls-mon-5",
      title: "Physical Education",
      subject: "PE",
      teacher: "Mr. Deepak Singh",
      date: dateKey(mon),
      startMinutes: 15 * 60,
      endMinutes: 16 * 60,
      allDay: false,
      calendarId: "arts",
      tone: "amber",
      type: "event",
      location: "Sports Ground",
    },

    // ── TUESDAY ──
    {
      id: "cls-tue-1",
      title: "Chemistry",
      subject: "Chemistry",
      teacher: "Ms. Anita Desai",
      date: dateKey(tue),
      startMinutes: 8 * 60,
      endMinutes: 9 * 60,
      allDay: false,
      calendarId: "science",
      tone: "blue",
      type: "event",
      location: "Lab 1",
    },
    {
      id: "cls-tue-2",
      title: "Mathematics",
      subject: "Mathematics",
      teacher: "Mr. Arjun Sharma",
      date: dateKey(tue),
      startMinutes: 9 * 60 + 15,
      endMinutes: 10 * 60 + 15,
      allDay: false,
      calendarId: "maths",
      tone: "violet",
      type: "event",
      location: "Room 101",
    },
    {
      id: "cls-tue-3",
      title: "Geography",
      subject: "Geography",
      teacher: "Mrs. Kavita Joshi",
      date: dateKey(tue),
      startMinutes: 11 * 60,
      endMinutes: 12 * 60,
      allDay: false,
      calendarId: "humanities",
      tone: "teal",
      type: "event",
      location: "Room 202",
    },
    {
      id: "cls-tue-4",
      title: "Hindi",
      subject: "Hindi",
      teacher: "Mr. Suresh Pandey",
      date: dateKey(tue),
      startMinutes: 13 * 60,
      endMinutes: 14 * 60,
      allDay: false,
      calendarId: "language",
      tone: "rose",
      type: "event",
      location: "Room 108",
    },
    {
      id: "cls-tue-5",
      title: "Art & Craft",
      subject: "Art",
      teacher: "Ms. Meera Pillai",
      date: dateKey(tue),
      startMinutes: 14 * 60 + 30,
      endMinutes: 15 * 60 + 30,
      allDay: false,
      calendarId: "arts",
      tone: "amber",
      type: "event",
      location: "Art Room",
    },

    // ── WEDNESDAY ──
    {
      id: "cls-wed-1",
      title: "Biology",
      subject: "Biology",
      teacher: "Dr. Neha Gupta",
      date: dateKey(wed),
      startMinutes: 8 * 60,
      endMinutes: 9 * 60,
      allDay: false,
      calendarId: "science",
      tone: "blue",
      type: "event",
      location: "Lab 3",
    },
    {
      id: "cls-wed-2",
      title: "English Literature",
      subject: "English",
      teacher: "Mrs. Sunita Verma",
      date: dateKey(wed),
      startMinutes: 9 * 60 + 15,
      endMinutes: 10 * 60 + 15,
      allDay: false,
      calendarId: "language",
      tone: "rose",
      type: "event",
      location: "Room 204",
    },
    {
      id: "cls-wed-3",
      title: "Mathematics",
      subject: "Mathematics",
      teacher: "Mr. Arjun Sharma",
      date: dateKey(wed),
      startMinutes: 11 * 60,
      endMinutes: 12 * 60,
      allDay: false,
      calendarId: "maths",
      tone: "violet",
      type: "event",
      location: "Room 101",
    },
    {
      id: "cls-wed-4",
      title: "Computer Science",
      subject: "Computer Science",
      teacher: "Mr. Vikram Rao",
      date: dateKey(wed),
      startMinutes: 13 * 60,
      endMinutes: 14 * 60 + 30,
      allDay: false,
      calendarId: "science",
      tone: "blue",
      type: "event",
      location: "Computer Lab",
    },

    // ── THURSDAY ──
    {
      id: "cls-thu-1",
      title: "Physics",
      subject: "Physics",
      teacher: "Ms. Priya Nair",
      date: dateKey(thu),
      startMinutes: 8 * 60,
      endMinutes: 9 * 60,
      allDay: false,
      calendarId: "science",
      tone: "blue",
      type: "event",
      location: "Lab 2",
    },
    {
      id: "cls-thu-2",
      title: "History",
      subject: "History",
      teacher: "Mr. Ravi Kulkarni",
      date: dateKey(thu),
      startMinutes: 9 * 60 + 15,
      endMinutes: 10 * 60 + 15,
      allDay: false,
      calendarId: "humanities",
      tone: "teal",
      type: "event",
      location: "Room 305",
    },
    {
      id: "cls-thu-3",
      title: "Chemistry",
      subject: "Chemistry",
      teacher: "Ms. Anita Desai",
      date: dateKey(thu),
      startMinutes: 11 * 60,
      endMinutes: 12 * 60,
      allDay: false,
      calendarId: "science",
      tone: "blue",
      type: "event",
      location: "Lab 1",
    },
    {
      id: "cls-thu-4",
      title: "Hindi",
      subject: "Hindi",
      teacher: "Mr. Suresh Pandey",
      date: dateKey(thu),
      startMinutes: 13 * 60,
      endMinutes: 14 * 60,
      allDay: false,
      calendarId: "language",
      tone: "rose",
      type: "event",
      location: "Room 108",
    },
    {
      id: "cls-thu-5",
      title: "Physical Education",
      subject: "PE",
      teacher: "Mr. Deepak Singh",
      date: dateKey(thu),
      startMinutes: 15 * 60,
      endMinutes: 16 * 60,
      allDay: false,
      calendarId: "arts",
      tone: "amber",
      type: "event",
      location: "Sports Ground",
    },

    // ── FRIDAY ──
    {
      id: "cls-fri-1",
      title: "Biology",
      subject: "Biology",
      teacher: "Dr. Neha Gupta",
      date: dateKey(fri),
      startMinutes: 8 * 60,
      endMinutes: 9 * 60,
      allDay: false,
      calendarId: "science",
      tone: "blue",
      type: "event",
      location: "Lab 3",
    },
    {
      id: "cls-fri-2",
      title: "Geography",
      subject: "Geography",
      teacher: "Mrs. Kavita Joshi",
      date: dateKey(fri),
      startMinutes: 9 * 60 + 15,
      endMinutes: 10 * 60 + 15,
      allDay: false,
      calendarId: "humanities",
      tone: "teal",
      type: "event",
      location: "Room 202",
    },
    {
      id: "cls-fri-3",
      title: "Computer Science",
      subject: "Computer Science",
      teacher: "Mr. Vikram Rao",
      date: dateKey(fri),
      startMinutes: 11 * 60,
      endMinutes: 12 * 60 + 30,
      allDay: false,
      calendarId: "science",
      tone: "blue",
      type: "event",
      location: "Computer Lab",
    },
    {
      id: "cls-fri-4",
      title: "Art & Craft",
      subject: "Art",
      teacher: "Ms. Meera Pillai",
      date: dateKey(fri),
      startMinutes: 13 * 60,
      endMinutes: 14 * 60,
      allDay: false,
      calendarId: "arts",
      tone: "amber",
      type: "event",
      location: "Art Room",
    },
    {
      id: "cls-fri-5",
      title: "Mathematics",
      subject: "Mathematics",
      teacher: "Mr. Arjun Sharma",
      date: dateKey(fri),
      startMinutes: 14 * 60 + 30,
      endMinutes: 15 * 60 + 30,
      allDay: false,
      calendarId: "maths",
      tone: "violet",
      type: "event",
      location: "Room 101",
    },
  ];
}
